install:
  # Updates the catalog.
  - sudo apt-get update -qq
  # Installs the packages.
  - sudo apt-get install python-pip curl -y
  # Installs the Python packages for Pelican.
  - sudo pip install pelican markdown

script:
  # Retrieves the Flex template
  - cd themes
  - wget https://github.com/alexandrevicenzi/Flex/archive/v1.1.tar.gz ; tar -xvf v1.1.tar.gz ; 
  - mv Flex-1.1/static/css/* mombacho/static/css/ ; rmdir Flex-1.1/static/css/
  - mv Flex-1.1/static/* mombacho/static/ ; rmdir Flex-1.1/static/
  - mv Flex-1.1/templates/partial/* mombacho/templates/partial/ ; rmdir Flex-1.1/templates/partial/
  - mv Flex-1.1/templates/* mombacho/templates/ ; rmdir Flex-1.1/templates/
  - mv Flex-1.1/* mombacho
  - rm -Rf Flex-1.1/
  - cd ..

  # Retrieves Leaflet library
  - cd themes/mombacho/static
  - wget http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.zip ; unzip leaflet.zip
  - mv images css
  - mv leaflet.css css
  - mv leaflet.js js
  - cd ../../..

  # Generates the package
  - cd ; cd XXX ; pelican

  - curl http://169.254.169.254/latest/meta-data/public-ipv4
  - make html
  - make serve

